name: process-shell

on:
  workflow_dispatch
  
jobs:
  process-shell:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: compile and test
      run: | 
        cd processes-shell
        gcc -o wish wish.c -Wall
        ./test-wish.sh
